.TH "__DRIcopySubBufferExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIcopySubBufferExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBcopySubBuffer\fP )(\fB__DRIdrawable\fP *drawable, int \fBx\fP, int \fBy\fP, int \fBw\fP, int \fBh\fP)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 135 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIcopySubBufferExtensionRec::base"

.PP
Définition à la ligne 136 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIcopySubBufferExtensionRec::copySubBuffer)(\fB__DRIdrawable\fP *drawable, int \fBx\fP, int \fBy\fP, int \fBw\fP, int \fBh\fP)"

.PP
Définition à la ligne 137 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
