.TH "__DRI2throttleExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRI2throttleExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBthrottle\fP )(\fB__DRIcontext\fP *ctx, \fB__DRIdrawable\fP *drawable, enum \fB__DRI2throttleReason\fP reason)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 301 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRI2throttleExtensionRec::base"

.PP
Définition à la ligne 302 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRI2throttleExtensionRec::throttle)(\fB__DRIcontext\fP *ctx, \fB__DRIdrawable\fP *drawable, enum \fB__DRI2throttleReason\fP reason)"

.PP
Définition à la ligne 303 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
