.TH "__DRIimageLookupExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIimageLookupExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fB__DRIimage\fP *(* \fBlookupEGLImage\fP )(\fB__DRIscreen\fP *screen, \fBvoid\fP *\fBimage\fP, \fBvoid\fP *loaderPrivate)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 965 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIimageLookupExtensionRec::base"

.PP
Définition à la ligne 966 du fichier dri_interface\&.h\&.
.SS "\fB__DRIimage\fP*(* __DRIimageLookupExtensionRec::lookupEGLImage)(\fB__DRIscreen\fP *screen, \fBvoid\fP *\fBimage\fP, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 968 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
