.TH "__DRI2configQueryExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRI2configQueryExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "int(* \fBconfigQueryb\fP )(\fB__DRIscreen\fP *screen, const char *var, \fBGLboolean\fP *\fBval\fP)"
.br
.ti -1c
.RI "int(* \fBconfigQueryi\fP )(\fB__DRIscreen\fP *screen, const char *var, \fBGLint\fP *\fBval\fP)"
.br
.ti -1c
.RI "int(* \fBconfigQueryf\fP )(\fB__DRIscreen\fP *screen, const char *var, \fBGLfloat\fP *\fBval\fP)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 979 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRI2configQueryExtensionRec::base"

.PP
Définition à la ligne 980 du fichier dri_interface\&.h\&.
.SS "int(* __DRI2configQueryExtensionRec::configQueryb)(\fB__DRIscreen\fP *screen, const char *var, \fBGLboolean\fP *\fBval\fP)"

.PP
Définition à la ligne 982 du fichier dri_interface\&.h\&.
.SS "int(* __DRI2configQueryExtensionRec::configQueryf)(\fB__DRIscreen\fP *screen, const char *var, \fBGLfloat\fP *\fBval\fP)"

.PP
Définition à la ligne 984 du fichier dri_interface\&.h\&.
.SS "int(* __DRI2configQueryExtensionRec::configQueryi)(\fB__DRIscreen\fP *screen, const char *var, \fBGLint\fP *\fBval\fP)"

.PP
Définition à la ligne 983 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
