.TH "__DRIbufferRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIbufferRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "unsigned int \fBattachment\fP"
.br
.ti -1c
.RI "unsigned int \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBpitch\fP"
.br
.ti -1c
.RI "unsigned int \fBcpp\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 738 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned int __DRIbufferRec::attachment"

.PP
Définition à la ligne 739 du fichier dri_interface\&.h\&.
.SS "unsigned int __DRIbufferRec::cpp"

.PP
Définition à la ligne 742 du fichier dri_interface\&.h\&.
.SS "unsigned int __DRIbufferRec::flags"

.PP
Définition à la ligne 743 du fichier dri_interface\&.h\&.
.SS "unsigned int __DRIbufferRec::name"

.PP
Définition à la ligne 740 du fichier dri_interface\&.h\&.
.SS "unsigned int __DRIbufferRec::pitch"

.PP
Définition à la ligne 741 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
