.TH "__DRIgetDrawableInfoExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIgetDrawableInfoExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBGLboolean\fP(* \fBgetDrawableInfo\fP )(\fB__DRIdrawable\fP *drawable, unsigned int *\fBindex\fP, unsigned int *stamp, int *\fBx\fP, int *\fBy\fP, int *\fBwidth\fP, int *\fBheight\fP, int *numClipRects, drm_clip_rect_t **pClipRects, int *backX, int *backY, int *numBackClipRects, drm_clip_rect_t **pBackClipRects, \fBvoid\fP *loaderPrivate)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 338 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIgetDrawableInfoExtensionRec::base"

.PP
Définition à la ligne 339 du fichier dri_interface\&.h\&.
.SS "\fBGLboolean\fP(*  __DRIgetDrawableInfoExtensionRec::getDrawableInfo)(\fB__DRIdrawable\fP *drawable, unsigned int *\fBindex\fP, unsigned int *stamp, int *\fBx\fP, int *\fBy\fP, int *\fBwidth\fP, int *\fBheight\fP, int *numClipRects, drm_clip_rect_t **pClipRects, int *backX, int *backY, int *numBackClipRects, drm_clip_rect_t **pBackClipRects, \fBvoid\fP *loaderPrivate)"
This function is used to get information about the position, size, and clip rects of a drawable\&. 
.PP
Définition à la ligne 345 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
