.TH "__DRIframebufferRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIframebufferRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "unsigned char * \fBbase\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBstride\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBdev_priv_size\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBdev_priv\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Framebuffer information record\&. Used by libGL to communicate information about the framebuffer to the driver's \fC__driCreateNewScreen\fP function\&.
.PP
In XFree86, most of this information is derrived from data returned by calling \fCXF86DRIGetDeviceInfo\fP\&.
.PP
\fBVoir également:\fP
.RS 4
XF86DRIGetDeviceInfo __DRIdisplayRec::createNewScreen __driUtilCreateNewScreen CallCreateNewScreen
.RE
.PP
\fBBogue\fP
.RS 4
This structure could be better named\&. 
.RE
.PP

.PP
Définition à la ligne 625 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned char* __DRIframebufferRec::base"
.PP
.nf
                 Framebuffer base address in the CPU's
.fi
.PP
 address space\&. This value is calculated by calling \fCdrmMap\fP on the framebuffer handle returned by \fCXF86DRIGetDeviceInfo\fP (or a similar function)\&. 
.PP
Définition à la ligne 626 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP* __DRIframebufferRec::dev_priv"
Pointer to the driver's dev-priv structure\&. 
.PP
Définition à la ligne 637 du fichier dri_interface\&.h\&.
.SS "int __DRIframebufferRec::dev_priv_size"
Size of the driver's dev-priv structure\&. 
.PP
Définition à la ligne 636 du fichier dri_interface\&.h\&.
.SS "int __DRIframebufferRec::height"
Pixel height of the framebuffer\&. 
.PP
Définition à la ligne 635 du fichier dri_interface\&.h\&.
.SS "int __DRIframebufferRec::size"
Framebuffer size, in bytes\&. 
.PP
Définition à la ligne 632 du fichier dri_interface\&.h\&.
.SS "int __DRIframebufferRec::stride"
Number of bytes from one line to the next\&. 
.PP
Définition à la ligne 633 du fichier dri_interface\&.h\&.
.SS "int __DRIframebufferRec::width"
Pixel width of the framebuffer\&. 
.PP
Définition à la ligne 634 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
