.TH "__DRIcoreExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIcoreExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fB__DRIscreen\fP *(* \fBcreateNewScreen\fP )(int screen, int fd, unsigned int sarea_handle, const \fB__DRIextension\fP **extensions, const \fB__DRIconfig\fP ***driverConfigs, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBdestroyScreen\fP )(\fB__DRIscreen\fP *screen)"
.br
.ti -1c
.RI "const \fB__DRIextension\fP **(* \fBgetExtensions\fP )(\fB__DRIscreen\fP *screen)"
.br
.ti -1c
.RI "int(* \fBgetConfigAttrib\fP )(const \fB__DRIconfig\fP *config, unsigned int attrib, unsigned int *\fBvalue\fP)"
.br
.ti -1c
.RI "int(* \fBindexConfigAttrib\fP )(const \fB__DRIconfig\fP *config, int \fBindex\fP, unsigned int *attrib, unsigned int *\fBvalue\fP)"
.br
.ti -1c
.RI "\fB__DRIdrawable\fP *(* \fBcreateNewDrawable\fP )(\fB__DRIscreen\fP *screen, const \fB__DRIconfig\fP *config, unsigned int drawable_id, unsigned int head, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBdestroyDrawable\fP )(\fB__DRIdrawable\fP *drawable)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBswapBuffers\fP )(\fB__DRIdrawable\fP *drawable)"
.br
.ti -1c
.RI "\fB__DRIcontext\fP *(* \fBcreateNewContext\fP )(\fB__DRIscreen\fP *screen, const \fB__DRIconfig\fP *config, \fB__DRIcontext\fP *shared, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "int(* \fBcopyContext\fP )(\fB__DRIcontext\fP *dest, \fB__DRIcontext\fP *\fBsrc\fP, unsigned long \fBmask\fP)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBdestroyContext\fP )(\fB__DRIcontext\fP *context)"
.br
.ti -1c
.RI "int(* \fBbindContext\fP )(\fB__DRIcontext\fP *ctx, \fB__DRIdrawable\fP *pdraw, \fB__DRIdrawable\fP *pread)"
.br
.ti -1c
.RI "int(* \fBunbindContext\fP )(\fB__DRIcontext\fP *ctx)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 550 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIcoreExtensionRec::base"

.PP
Définition à la ligne 551 du fichier dri_interface\&.h\&.
.SS "int(* __DRIcoreExtensionRec::bindContext)(\fB__DRIcontext\fP *ctx, \fB__DRIdrawable\fP *pdraw, \fB__DRIdrawable\fP *pread)"

.PP
Définition à la ligne 591 du fichier dri_interface\&.h\&.
.SS "int(* __DRIcoreExtensionRec::copyContext)(\fB__DRIcontext\fP *dest, \fB__DRIcontext\fP *\fBsrc\fP, unsigned long \fBmask\fP)"

.PP
Définition à la ligne 585 du fichier dri_interface\&.h\&.
.SS "\fB__DRIcontext\fP*(* __DRIcoreExtensionRec::createNewContext)(\fB__DRIscreen\fP *screen, const \fB__DRIconfig\fP *config, \fB__DRIcontext\fP *shared, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 580 du fichier dri_interface\&.h\&.
.SS "\fB__DRIdrawable\fP*(* __DRIcoreExtensionRec::createNewDrawable)(\fB__DRIscreen\fP *screen, const \fB__DRIconfig\fP *config, unsigned int drawable_id, unsigned int head, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 570 du fichier dri_interface\&.h\&.
.SS "\fB__DRIscreen\fP*(* __DRIcoreExtensionRec::createNewScreen)(int screen, int fd, unsigned int sarea_handle, const \fB__DRIextension\fP **extensions, const \fB__DRIconfig\fP ***driverConfigs, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 553 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIcoreExtensionRec::destroyContext)(\fB__DRIcontext\fP *context)"

.PP
Définition à la ligne 589 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIcoreExtensionRec::destroyDrawable)(\fB__DRIdrawable\fP *drawable)"

.PP
Définition à la ligne 576 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIcoreExtensionRec::destroyScreen)(\fB__DRIscreen\fP *screen)"

.PP
Définition à la ligne 559 du fichier dri_interface\&.h\&.
.SS "int(* __DRIcoreExtensionRec::getConfigAttrib)(const \fB__DRIconfig\fP *config, unsigned int attrib, unsigned int *\fBvalue\fP)"

.PP
Définition à la ligne 563 du fichier dri_interface\&.h\&.
.SS "const \fB__DRIextension\fP**(* __DRIcoreExtensionRec::getExtensions)(\fB__DRIscreen\fP *screen)"

.PP
Définition à la ligne 561 du fichier dri_interface\&.h\&.
.SS "int(* __DRIcoreExtensionRec::indexConfigAttrib)(const \fB__DRIconfig\fP *config, int \fBindex\fP, unsigned int *attrib, unsigned int *\fBvalue\fP)"

.PP
Définition à la ligne 567 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIcoreExtensionRec::swapBuffers)(\fB__DRIdrawable\fP *drawable)"

.PP
Définition à la ligne 578 du fichier dri_interface\&.h\&.
.SS "int(* __DRIcoreExtensionRec::unbindContext)(\fB__DRIcontext\fP *ctx)"

.PP
Définition à la ligne 595 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
