.TH "__DRIversionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIversionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBmajor\fP"
.br
.ti -1c
.RI "int \fBminor\fP"
.br
.ti -1c
.RI "int \fBpatch\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Stored version of some component (i\&.e\&., server-side DRI module, kernel-side DRM, etc\&.)\&.
.PP
\fBA faire\fP
.RS 4
There are several data structures that explicitly store a major version, minor version, and patch level\&. These structures should be modified to have a \fC\fB__DRIversionRec\fP\fP instead\&. 
.RE
.PP

.PP
Définition à la ligne 607 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "int __DRIversionRec::major"
Major version number\&. 
.PP
Définition à la ligne 608 du fichier dri_interface\&.h\&.
.SS "int __DRIversionRec::minor"
Minor version number\&. 
.PP
Définition à la ligne 609 du fichier dri_interface\&.h\&.
.SS "int __DRIversionRec::patch"
Patch-level\&. 
.PP
Définition à la ligne 610 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
