.TH "__DRIswapControlExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIswapControlExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBsetSwapInterval\fP )(\fB__DRIdrawable\fP *drawable, unsigned int inteval)"
.br
.ti -1c
.RI "unsigned int(* \fBgetSwapInterval\fP )(\fB__DRIdrawable\fP *drawable)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 146 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIswapControlExtensionRec::base"

.PP
Définition à la ligne 147 du fichier dri_interface\&.h\&.
.SS "unsigned int(* __DRIswapControlExtensionRec::getSwapInterval)(\fB__DRIdrawable\fP *drawable)"

.PP
Définition à la ligne 149 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIswapControlExtensionRec::setSwapInterval)(\fB__DRIdrawable\fP *drawable, unsigned int inteval)"

.PP
Définition à la ligne 148 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
