.TH "__DRIswrastExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIswrastExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fB__DRIscreen\fP *(* \fBcreateNewScreen\fP )(int screen, const \fB__DRIextension\fP **extensions, const \fB__DRIconfig\fP ***driver_configs, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "\fB__DRIdrawable\fP *(* \fBcreateNewDrawable\fP )(\fB__DRIscreen\fP *screen, const \fB__DRIconfig\fP *config, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "\fB__DRIcontext\fP *(* \fBcreateNewContextForAPI\fP )(\fB__DRIscreen\fP *screen, int api, const \fB__DRIconfig\fP *config, \fB__DRIcontext\fP *shared, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fB__DRIcontext\fP *(* \fBcreateContextAttribs\fP )(\fB__DRIscreen\fP *screen, int api, const \fB__DRIconfig\fP *config, \fB__DRIcontext\fP *shared, unsigned num_attribs, const uint32_t *\fBattribs\fP, unsigned *error, \fBvoid\fP *loaderPrivate)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 684 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIswrastExtensionRec::base"

.PP
Définition à la ligne 685 du fichier dri_interface\&.h\&.
.SS "\fB__DRIcontext\fP*(* __DRIswrastExtensionRec::createContextAttribs)(\fB__DRIscreen\fP *screen, int api, const \fB__DRIconfig\fP *config, \fB__DRIcontext\fP *shared, unsigned num_attribs, const uint32_t *\fBattribs\fP, unsigned *error, \fBvoid\fP *loaderPrivate)"
Create a context for a particular API with a set of attributes
.PP
\fBDepuis:\fP
.RS 4
version 3
.RE
.PP
\fBVoir également:\fP
.RS 4
\fB__DRIdri2ExtensionRec::createContextAttribs\fP 
.RE
.PP

.PP
Définition à la ligne 710 du fichier dri_interface\&.h\&.
.SS "\fB__DRIcontext\fP*(* __DRIswrastExtensionRec::createNewContextForAPI)(\fB__DRIscreen\fP *screen, int api, const \fB__DRIconfig\fP *config, \fB__DRIcontext\fP *shared, \fBvoid\fP *\fBdata\fP)"

.PP
Définition à la ligne 697 du fichier dri_interface\&.h\&.
.SS "\fB__DRIdrawable\fP*(* __DRIswrastExtensionRec::createNewDrawable)(\fB__DRIscreen\fP *screen, const \fB__DRIconfig\fP *config, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 692 du fichier dri_interface\&.h\&.
.SS "\fB__DRIscreen\fP*(* __DRIswrastExtensionRec::createNewScreen)(int screen, const \fB__DRIextension\fP **extensions, const \fB__DRIconfig\fP ***driver_configs, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 687 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
