.TH "__DRIframeTrackingExtensionRec" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIframeTrackingExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "int(* \fBframeTracking\fP )(\fB__DRIdrawable\fP *drawable, \fBGLboolean\fP \fBenable\fP)"
.br
.ti -1c
.RI "int(* \fBqueryFrameTracking\fP )(\fB__DRIdrawable\fP *drawable, int64_t *sbc, int64_t *missedFrames, float *lastMissedUsage, float *\fBusage\fP)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 157 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIframeTrackingExtensionRec::base"

.PP
Définition à la ligne 158 du fichier dri_interface\&.h\&.
.SS "int(* __DRIframeTrackingExtensionRec::frameTracking)(\fB__DRIdrawable\fP *drawable, \fBGLboolean\fP \fBenable\fP)"
Enable or disable frame usage tracking\&.
.PP
\fBDepuis:\fP
.RS 4
Internal API version 20030317\&. 
.RE
.PP

.PP
Définition à la ligne 165 du fichier dri_interface\&.h\&.
.SS "int(* __DRIframeTrackingExtensionRec::queryFrameTracking)(\fB__DRIdrawable\fP *drawable, int64_t *sbc, int64_t *missedFrames, float *lastMissedUsage, float *\fBusage\fP)"
Retrieve frame usage information\&.
.PP
\fBDepuis:\fP
.RS 4
Internal API version 20030317\&. 
.RE
.PP

.PP
Définition à la ligne 172 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
