.TH "Case" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Case \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CTGameTable\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCase\fP ()"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "bool \fBm_used\fP"
.br
.ti -1c
.RI "\fBCVector3\fP \fBm_color\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 14 du fichier CTGameTable\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Case::Case ()\fC [inline]\fP"

.PP
Définition à la ligne 15 du fichier CTGameTable\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCVector3\fP Case::m_color"

.PP
Définition à la ligne 17 du fichier CTGameTable\&.h\&.
.SS "bool Case::m_used"

.PP
Définition à la ligne 16 du fichier CTGameTable\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
