.TH "CL1Piece" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CL1Piece \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CL1Piece\&.h>\fP
.PP
Est dérivée de \fBCPieceAbstract\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCL1Piece\fP (int iX, int iY, const \fBCVector3\fP &\fBcolor\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBTurn\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Description détaillée"
.PP 
Définition à la ligne 6 du fichier CL1Piece\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CL1Piece::CL1Piece (intiX, intiY, const \fBCVector3\fP &color)"

.PP
Définition à la ligne 4 du fichier CL1Piece\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP CL1Piece::Turn ()"

.PP
Définition à la ligne 19 du fichier CL1Piece\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
