.TH "/home/cj/workspace/Tetris/src/tetris/CL2Piece.cpp" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/tetris/CL2Piece.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CL2Piece\&.h'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
