.TH "/home/cj/workspace/Tetris/src/math/CMatrix44.h" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/math/CMatrix44.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CVector3\&.h'\fP
.br
\fC#include 'CVector4\&.h'\fP
.br
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCMatrix44\fP"
.br
.RI "\fI[SmrCoreMath] define float 4*4 Matrix \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &\fBstream\fP, const \fBCMatrix44\fP &mat)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::ostream& operator<< (std::ostream &stream, const \fBCMatrix44\fP &mat)\fC [inline]\fP"

.PP
Définition à la ligne 237 du fichier CMatrix44\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
