.TH "CMatrix44" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMatrix44 \- 
.PP
[SmrCoreMath] define float 4*4 Matrix  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CMatrix44\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCMatrix44\fP ()"
.br
.RI "\fIdefault constructor, init matrix to identity \fP"
.ti -1c
.RI "\fBCMatrix44\fP (float *buff)"
.br
.RI "\fIconstructor, init matrix with a buffer of values \fP"
.ti -1c
.RI "\fBCMatrix44\fP (const \fBCVector3\fP &\fBx\fP, const \fBCVector3\fP &\fBy\fP, const \fBCVector3\fP &\fBz\fP)"
.br
.RI "\fIconstructor, init matrix with 3 axes \fP"
.ti -1c
.RI "\fBvoid\fP \fBSetTranslation\fP (const \fBCVector3\fP &vec)"
.br
.RI "\fIset translation \fP"
.ti -1c
.RI "\fBvoid\fP \fBSetTranslation\fP (const \fBCVector4\fP &vec)"
.br
.ti -1c
.RI "\fBvoid\fP \fBTranslate\fP (const \fBCVector3\fP &vec)"
.br
.RI "\fIAdd translation\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBTranslate\fP (const \fBCVector4\fP &vec)"
.br
.ti -1c
.RI "\fBCVector3\fP \fBGetTranslation\fP () const "
.br
.RI "\fIget translation \fP"
.ti -1c
.RI "\fBCVector3\fP \fBGetScale\fP ()"
.br
.RI "\fIget scale \fP"
.ti -1c
.RI "\fBCVector3\fP \fBGetXAxis\fP ()"
.br
.RI "\fIget axis x,y,z \fP"
.ti -1c
.RI "\fBCVector3\fP \fBGetYAxis\fP ()"
.br
.ti -1c
.RI "\fBCVector3\fP \fBGetZAxis\fP ()"
.br
.ti -1c
.RI "const float & \fBoperator()\fP (unsigned int \fBrow\fP, unsigned int col) const "
.br
.RI "\fIoperator to get a value into matrix \fP"
.ti -1c
.RI "float & \fBoperator()\fP (unsigned int \fBrow\fP, unsigned int col)"
.br
.ti -1c
.RI "float \fBdet\fP ()"
.br
.RI "\fIget determinant of matrix \fP"
.ti -1c
.RI "\fBvoid\fP \fBinvert\fP ()"
.br
.RI "\fIinvert the matrix \fP"
.ti -1c
.RI "\fBvoid\fP \fBtranspose\fP ()"
.br
.RI "\fIinvert the matrix \fP"
.ti -1c
.RI "\fBCMatrix44\fP \fBoperator*\fP (const \fBCMatrix44\fP &\fBm\fP) const "
.br
.RI "\fIoperator to multiply current matrix with other matrix \fP"
.ti -1c
.RI "\fBCVector4\fP \fBoperator*\fP (const \fBCVector4\fP &\fBv\fP) const "
.br
.RI "\fIoperator to multiply current matrix with other matrix \fP"
.ti -1c
.RI "\fBCVector3\fP \fBoperator*\fP (const \fBCVector3\fP &\fBv\fP) const "
.br
.RI "\fIoperator to multiply current matrix with other matrix \fP"
.ti -1c
.RI "\fBvoid\fP \fBPerspective\fP (float fovy, float aspect, float \fBzNear\fP, float \fBzFar\fP)"
.br
.RI "\fIspecifies a viewing frustum into the world coordinate system (http://www.opengl.org/sdk/docs/man/xhtml/gluPerspective.xml) \fP"
.ti -1c
.RI "\fBvoid\fP \fBLookAt\fP (const \fBCVector3\fP &eye, const \fBCVector3\fP &center, const \fBCVector3\fP &up)"
.br
.RI "\fIcreates a viewing matrix derived from an eye point (http://www.opengl.org/sdk/docs/man/xhtml/gluLookAt.xml) \fP"
.ti -1c
.RI "\fBvoid\fP \fBOrthographic\fP (float \fBleft\fP, float \fBright\fP, float \fBbottom\fP, float \fBtop\fP, float nearVal, float farVal)"
.br
.RI "\fIcreates a Orthographic (http://www.opengl.org/sdk/docs/man/xhtml/glOrtho.xml) \fP"
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCMatrix44\fP &\fBt\fP) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCMatrix44\fP &\fBt\fP) const "
.br
.in -1c
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static \fBCMatrix44\fP \fBCreatePerspective\fP (float fovy, float aspect, float \fBzNear\fP, float \fBzFar\fP)"
.br
.ti -1c
.RI "static \fBCMatrix44\fP \fBCreateLookAt\fP (const \fBCVector3\fP &eye, const \fBCVector3\fP &center, const \fBCVector3\fP &up)"
.br
.ti -1c
.RI "static \fBCMatrix44\fP \fBCreateOrthographic\fP (float \fBleft\fP, float \fBright\fP, float \fBbottom\fP, float \fBtop\fP, float nearVal, float farVal)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   float \fBm\fP [4][4]"
.br
.ti -1c
.RI "   float \fBb\fP [16]"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SS "Attributs publics statiques"

.in +1c
.ti -1c
.RI "static \fBCMatrix44\fP \fBIdentity\fP = \fBCMatrix44\fP()"
.br
.RI "\fIidentity transformation \fP"
.in -1c
.SH "Description détaillée"
.PP 
[SmrCoreMath] define float 4*4 Matrix 
.PP
Définition à la ligne 56 du fichier CMatrix44\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CMatrix44::CMatrix44 ()\fC [inline]\fP"

.PP
default constructor, init matrix to identity 
.PP
Définition à la ligne 72 du fichier CMatrix44\&.h\&.
.SS "CMatrix44::CMatrix44 (float *buff)"

.PP
constructor, init matrix with a buffer of values \fBParamètres:\fP
.RS 4
\fIbuffer\fP of values 
.RE
.PP

.PP
Définition à la ligne 31 du fichier CMatrix44\&.cpp\&.
.SS "CMatrix44::CMatrix44 (const \fBCVector3\fP &x, const \fBCVector3\fP &y, const \fBCVector3\fP &z)"

.PP
constructor, init matrix with 3 axes \fBParamètres:\fP
.RS 4
\fIaxis\fP 1 
.br
\fIaxis\fP 2 
.br
\fIaxis\fP 3 
.RE
.PP

.PP
Définition à la ligne 20 du fichier CMatrix44\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBCMatrix44\fP CMatrix44::CreateLookAt (const \fBCVector3\fP &eye, const \fBCVector3\fP &center, const \fBCVector3\fP &up)\fC [static]\fP"

.PP
Définition à la ligne 342 du fichier CMatrix44\&.cpp\&.
.SS "\fBCMatrix44\fP CMatrix44::CreateOrthographic (floatleft, floatright, floatbottom, floattop, floatnearVal, floatfarVal)\fC [static]\fP"

.PP
Définition à la ligne 366 du fichier CMatrix44\&.cpp\&.
.SS "\fBCMatrix44\fP CMatrix44::CreatePerspective (floatfovy, floataspect, floatzNear, floatzFar)\fC [static]\fP"

.PP
Définition à la ligne 306 du fichier CMatrix44\&.cpp\&.
.SS "float CMatrix44::det ()"

.PP
get determinant of matrix \fBRenvoie:\fP
.RS 4
float of determinant 
.RE
.PP

.PP
Définition à la ligne 176 du fichier CMatrix44\&.cpp\&.
.SS "\fBCVector3\fP CMatrix44::GetScale ()"

.PP
get scale \fBRenvoie:\fP
.RS 4
scale 
.RE
.PP

.PP
Définition à la ligne 374 du fichier CMatrix44\&.cpp\&.
.SS "\fBCVector3\fP CMatrix44::GetTranslation () const\fC [inline]\fP"

.PP
get translation \fBRenvoie:\fP
.RS 4
translation 
.RE
.PP

.PP
Définition à la ligne 295 du fichier CMatrix44\&.h\&.
.SS "\fBCVector3\fP CMatrix44::GetXAxis ()\fC [inline]\fP"

.PP
get axis x,y,z \fBRenvoie:\fP
.RS 4
axis 
.RE
.PP

.PP
Définition à la ligne 125 du fichier CMatrix44\&.h\&.
.SS "\fBCVector3\fP CMatrix44::GetYAxis ()\fC [inline]\fP"

.PP
Définition à la ligne 129 du fichier CMatrix44\&.h\&.
.SS "\fBCVector3\fP CMatrix44::GetZAxis ()\fC [inline]\fP"

.PP
Définition à la ligne 133 du fichier CMatrix44\&.h\&.
.SS "\fBvoid\fP CMatrix44::invert ()"

.PP
invert the matrix 
.PP
Définition à la ligne 202 du fichier CMatrix44\&.cpp\&.
.SS "\fBvoid\fP CMatrix44::LookAt (const \fBCVector3\fP &eye, const \fBCVector3\fP &center, const \fBCVector3\fP &up)"

.PP
creates a viewing matrix derived from an eye point (http://www.opengl.org/sdk/docs/man/xhtml/gluLookAt.xml) \fBParamètres:\fP
.RS 4
\fISpecifies\fP the position of the eye point\&. 
.br
\fISpecifies\fP the position of the reference point 
.br
\fISpecifies\fP the direction of the up vector 
.RE
.PP

.PP
Définition à la ligne 319 du fichier CMatrix44\&.cpp\&.
.SS "bool CMatrix44::operator!= (const \fBCMatrix44\fP &t) const\fC [inline]\fP"

.PP
Définition à la ligne 223 du fichier CMatrix44\&.h\&.
.SS "const float & CMatrix44::operator() (unsigned introw, unsigned intcol) const\fC [inline]\fP"

.PP
operator to get a value into matrix \fBRenvoie:\fP
.RS 4
translation 
.RE
.PP

.PP
Définition à la ligne 303 du fichier CMatrix44\&.h\&.
.SS "float & CMatrix44::operator() (unsigned introw, unsigned intcol)\fC [inline]\fP"

.PP
Définition à la ligne 309 du fichier CMatrix44\&.h\&.
.SS "\fBCMatrix44\fP CMatrix44::operator* (const \fBCMatrix44\fP &m) const"

.PP
operator to multiply current matrix with other matrix \fBRenvoie:\fP
.RS 4
result matrinx 
.RE
.PP

.PP
Définition à la ligne 42 du fichier CMatrix44\&.cpp\&.
.SS "\fBCVector4\fP CMatrix44::operator* (const \fBCVector4\fP &v) const"

.PP
operator to multiply current matrix with other matrix \fBRenvoie:\fP
.RS 4
result matrinx 
.RE
.PP

.PP
Définition à la ligne 70 du fichier CMatrix44\&.cpp\&.
.SS "\fBCVector3\fP CMatrix44::operator* (const \fBCVector3\fP &v) const"

.PP
operator to multiply current matrix with other matrix \fBRenvoie:\fP
.RS 4
result matrinx 
.RE
.PP

.PP
Définition à la ligne 79 du fichier CMatrix44\&.cpp\&.
.SS "bool CMatrix44::operator== (const \fBCMatrix44\fP &t) const\fC [inline]\fP"

.PP
Définition à la ligne 214 du fichier CMatrix44\&.h\&.
.SS "\fBvoid\fP CMatrix44::Orthographic (floatleft, floatright, floatbottom, floattop, floatnearVal, floatfarVal)"

.PP
creates a Orthographic (http://www.opengl.org/sdk/docs/man/xhtml/glOrtho.xml) \fBParamètres:\fP
.RS 4
\fISpecify\fP the coordinates for the left and right vertical clipping planes 
.br
\fISpecify\fP the coordinates for the bottom and top horizontal clipping planes\&. 
.br
\fISpecify\fP the distances to the nearer and farther depth clipping planes\&. These values are negative if the plane is to be behind the viewer 
.RE
.PP

.PP
Définition à la ligne 350 du fichier CMatrix44\&.cpp\&.
.SS "\fBvoid\fP CMatrix44::Perspective (floatfovy, floataspect, floatzNear, floatzFar)"

.PP
specifies a viewing frustum into the world coordinate system (http://www.opengl.org/sdk/docs/man/xhtml/gluPerspective.xml) \fBParamètres:\fP
.RS 4
\fISpecifies\fP the field of view angle, in degrees, in the y direction\&. 
.br
\fISpecifies\fP the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height) 
.br
\fISpecifies\fP the distance from the viewer to the near clipping plane (always positive) 
.br
\fISpecifies\fP the distance from the viewer to the far clipping plane (always positive) 
.RE
.PP

.PP
Définition à la ligne 284 du fichier CMatrix44\&.cpp\&.
.SS "\fBvoid\fP CMatrix44::SetTranslation (const \fBCVector3\fP &vec)\fC [inline]\fP"

.PP
set translation \fBParamètres:\fP
.RS 4
\fItranslation\fP 
.RE
.PP

.PP
Définition à la ligne 265 du fichier CMatrix44\&.h\&.
.SS "\fBvoid\fP CMatrix44::SetTranslation (const \fBCVector4\fP &vec)\fC [inline]\fP"

.PP
Définition à la ligne 272 du fichier CMatrix44\&.h\&.
.SS "\fBvoid\fP CMatrix44::Translate (const \fBCVector3\fP &vec)\fC [inline]\fP"

.PP
Add translation\&. \fBParamètres:\fP
.RS 4
\fItranslation\fP 
.RE
.PP

.PP
Définition à la ligne 280 du fichier CMatrix44\&.h\&.
.SS "\fBvoid\fP CMatrix44::Translate (const \fBCVector4\fP &vec)\fC [inline]\fP"

.PP
Définition à la ligne 287 du fichier CMatrix44\&.h\&.
.SS "\fBvoid\fP CMatrix44::transpose ()"

.PP
invert the matrix 
.PP
Définition à la ligne 190 du fichier CMatrix44\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "union { \&.\&.\&. } "

.SS "float CMatrix44::b[16]"

.PP
Définition à la ligne 63 du fichier CMatrix44\&.h\&.
.SS "\fBCMatrix44\fP CMatrix44::Identity = \fBCMatrix44\fP()\fC [static]\fP"

.PP
identity transformation 
.PP
Définition à la ligne 228 du fichier CMatrix44\&.h\&.
.SS "float CMatrix44::m[4][4]"

.PP
Définition à la ligne 62 du fichier CMatrix44\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
