.TH "/home/cj/workspace/Tetris/src/math/CMatrix44.cpp" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/math/CMatrix44.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CMatrix44\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBN_MATRIXDEFS_H\fP"
.br
.ti -1c
.RI "#define \fBM00\fP   \fBm\fP[0][0]"
.br
.ti -1c
.RI "#define \fBM01\fP   \fBm\fP[1][0]"
.br
.ti -1c
.RI "#define \fBM02\fP   \fBm\fP[2][0]"
.br
.ti -1c
.RI "#define \fBM03\fP   \fBm\fP[3][0]"
.br
.ti -1c
.RI "#define \fBM10\fP   \fBm\fP[0][1]"
.br
.ti -1c
.RI "#define \fBM11\fP   \fBm\fP[1][1]"
.br
.ti -1c
.RI "#define \fBM12\fP   \fBm\fP[2][1]"
.br
.ti -1c
.RI "#define \fBM13\fP   \fBm\fP[3][1]"
.br
.ti -1c
.RI "#define \fBM20\fP   \fBm\fP[0][2]"
.br
.ti -1c
.RI "#define \fBM21\fP   \fBm\fP[1][2]"
.br
.ti -1c
.RI "#define \fBM22\fP   \fBm\fP[2][2]"
.br
.ti -1c
.RI "#define \fBM23\fP   \fBm\fP[3][2]"
.br
.ti -1c
.RI "#define \fBM30\fP   \fBm\fP[0][3]"
.br
.ti -1c
.RI "#define \fBM31\fP   \fBm\fP[1][3]"
.br
.ti -1c
.RI "#define \fBM32\fP   \fBm\fP[2][3]"
.br
.ti -1c
.RI "#define \fBM33\fP   \fBm\fP[3][3]"
.br
.ti -1c
.RI "#define \fBswap\fP(\fBx\fP, \fBy\fP)   { float \fBt\fP=\fBx\fP; \fBx\fP=\fBy\fP; \fBy\fP=\fBt\fP; }"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define M00   \fBm\fP[0][0]"

.PP
Définition à la ligne 154 du fichier CMatrix44\&.cpp\&.
.SS "#define M01   \fBm\fP[1][0]"

.PP
Définition à la ligne 155 du fichier CMatrix44\&.cpp\&.
.SS "#define M02   \fBm\fP[2][0]"

.PP
Définition à la ligne 156 du fichier CMatrix44\&.cpp\&.
.SS "#define M03   \fBm\fP[3][0]"

.PP
Définition à la ligne 157 du fichier CMatrix44\&.cpp\&.
.SS "#define M10   \fBm\fP[0][1]"

.PP
Définition à la ligne 158 du fichier CMatrix44\&.cpp\&.
.SS "#define M11   \fBm\fP[1][1]"

.PP
Définition à la ligne 159 du fichier CMatrix44\&.cpp\&.
.SS "#define M12   \fBm\fP[2][1]"

.PP
Définition à la ligne 160 du fichier CMatrix44\&.cpp\&.
.SS "#define M13   \fBm\fP[3][1]"

.PP
Définition à la ligne 161 du fichier CMatrix44\&.cpp\&.
.SS "#define M20   \fBm\fP[0][2]"

.PP
Définition à la ligne 162 du fichier CMatrix44\&.cpp\&.
.SS "#define M21   \fBm\fP[1][2]"

.PP
Définition à la ligne 163 du fichier CMatrix44\&.cpp\&.
.SS "#define M22   \fBm\fP[2][2]"

.PP
Définition à la ligne 164 du fichier CMatrix44\&.cpp\&.
.SS "#define M23   \fBm\fP[3][2]"

.PP
Définition à la ligne 165 du fichier CMatrix44\&.cpp\&.
.SS "#define M30   \fBm\fP[0][3]"

.PP
Définition à la ligne 166 du fichier CMatrix44\&.cpp\&.
.SS "#define M31   \fBm\fP[1][3]"

.PP
Définition à la ligne 167 du fichier CMatrix44\&.cpp\&.
.SS "#define M32   \fBm\fP[2][3]"

.PP
Définition à la ligne 168 du fichier CMatrix44\&.cpp\&.
.SS "#define M33   \fBm\fP[3][3]"

.PP
Définition à la ligne 169 du fichier CMatrix44\&.cpp\&.
.SS "#define N_MATRIXDEFS_H"

.PP
Définition à la ligne 152 du fichier CMatrix44\&.cpp\&.
.SS "#define swap(\fBx\fP, \fBy\fP)   { float \fBt\fP=\fBx\fP; \fBx\fP=\fBy\fP; \fBy\fP=\fBt\fP; }"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
