.TH "COPiece" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COPiece \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <COPiece\&.h>\fP
.PP
Est dérivée de \fBCPieceAbstract\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCOPiece\fP (int iX, int iY, const \fBCVector3\fP &\fBcolor\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBTurn\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Description détaillée"
.PP 
Définition à la ligne 7 du fichier COPiece\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "COPiece::COPiece (intiX, intiY, const \fBCVector3\fP &color)"

.PP
Définition à la ligne 4 du fichier COPiece\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP COPiece::Turn ()"

.PP
Définition à la ligne 17 du fichier COPiece\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
