.TH "/home/cj/workspace/Tetris/src/tetris/CPieceAbstract.h" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/tetris/CPieceAbstract.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCPieceAbstract\fP"
.br
.RI "\fIclasse \fBCPieceAbstract\fP abstraite \fP"
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef vector< int > \fBTPieceRow\fP"
.br
.ti -1c
.RI "typedef vector< \fBTPieceRow\fP > \fBTPieceTable\fP"
.br
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "typedef vector<int> \fBTPieceRow\fP"

.PP
Définition à la ligne 14 du fichier CPieceAbstract\&.h\&.
.SS "typedef vector<\fBTPieceRow\fP> \fBTPieceTable\fP"

.PP
Définition à la ligne 15 du fichier CPieceAbstract\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
