.TH "CRandomizer" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRandomizer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CRandomizer\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "int \fBNext\fP ()"
.br
.ti -1c
.RI "\fBCRandomizer\fP ()"
.br
.ti -1c
.RI "\fBCRandomizer\fP (unsigned int sizeList, unsigned int maxRand)"
.br
.ti -1c
.RI "int \fBFirst\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 15 du fichier CRandomizer\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CRandomizer::CRandomizer (\fBvoid\fP)"

.PP
Définition à la ligne 12 du fichier CRandomizer\&.cpp\&.
.SS "CRandomizer::CRandomizer (unsigned intsizeList, unsigned intmaxRand)"

.PP
Définition à la ligne 20 du fichier CRandomizer\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "int CRandomizer::First ()"

.PP
Définition à la ligne 57 du fichier CRandomizer\&.cpp\&.
.SS "int CRandomizer::Next ()"

.PP
Définition à la ligne 40 du fichier CRandomizer\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
