.TH "/home/cj/workspace/Tetris/src/appliBase/CRenderer.cpp" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/appliBase/CRenderer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CRenderer\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
