.TH "/home/cj/workspace/Tetris/src/tetris/CTetrisGame.h" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/tetris/CTetrisGame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CPieceAbstract\&.h'\fP
.br
\fC#include 'CIPiece\&.h'\fP
.br
\fC#include 'CTPiece\&.h'\fP
.br
\fC#include 'COPiece\&.h'\fP
.br
\fC#include 'CL1Piece\&.h'\fP
.br
\fC#include 'CL2Piece\&.h'\fP
.br
\fC#include 'CZ1Piece\&.h'\fP
.br
\fC#include 'CZ2Piece\&.h'\fP
.br
\fC#include 'CTGameTable\&.h'\fP
.br
\fC#include 'CRandomizer\&.h'\fP
.br
\fC#include 'TetrisUtils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCTetrisGame\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CTETRIS_GAME_H__\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define __CTETRIS_GAME_H__"

.PP
Définition à la ligne 9 du fichier CTetrisGame\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
