.TH "/home/cj/workspace/Tetris/src/tetris/CTGameTable.cpp" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/tetris/CTGameTable.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CTGameTable\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const \fBCTGameTable\fP &tab)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "ostream& operator<< (ostream &out, const \fBCTGameTable\fP &tab)"

.PP
Définition à la ligne 12 du fichier CTGameTable\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
