.TH "CTPiece" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTPiece \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CTPiece\&.h>\fP
.PP
Est dérivée de \fBCPieceAbstract\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBCTPiece\fP (int iX, int iY, const \fBCVector3\fP &\fBcolor\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBTurn\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Description détaillée"
.PP 
Définition à la ligne 7 du fichier CTPiece\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "CTPiece::CTPiece (intiX, intiY, const \fBCVector3\fP &color)"

.PP
Définition à la ligne 4 du fichier CTPiece\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP CTPiece::Turn ()"

.PP
Définition à la ligne 19 du fichier CTPiece\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
