.TH "/home/cj/workspace/Tetris/src/glut/glu_mangle.h" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/glut/glu_mangle.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBgluLookAt\fP   mgluLookAt"
.br
.ti -1c
.RI "#define \fBgluOrtho2D\fP   mgluOrtho2D"
.br
.ti -1c
.RI "#define \fBgluPerspective\fP   mgluPerspective"
.br
.ti -1c
.RI "#define \fBgluPickMatrix\fP   mgluPickMatrix"
.br
.ti -1c
.RI "#define \fBgluProject\fP   mgluProject"
.br
.ti -1c
.RI "#define \fBgluUnProject\fP   mgluUnProject"
.br
.ti -1c
.RI "#define \fBgluErrorString\fP   mgluErrorString"
.br
.ti -1c
.RI "#define \fBgluScaleImage\fP   mgluScaleImage"
.br
.ti -1c
.RI "#define \fBgluBuild1DMipmaps\fP   mgluBuild1DMipmaps"
.br
.ti -1c
.RI "#define \fBgluBuild2DMipmaps\fP   mgluBuild2DMipmaps"
.br
.ti -1c
.RI "#define \fBgluNewQuadric\fP   mgluNewQuadric"
.br
.ti -1c
.RI "#define \fBgluDeleteQuadric\fP   mgluDeleteQuadric"
.br
.ti -1c
.RI "#define \fBgluQuadricDrawStyle\fP   mgluQuadricDrawStyle"
.br
.ti -1c
.RI "#define \fBgluQuadricOrientation\fP   mgluQuadricOrientation"
.br
.ti -1c
.RI "#define \fBgluQuadricNormals\fP   mgluQuadricNormals"
.br
.ti -1c
.RI "#define \fBgluQuadricTexture\fP   mgluQuadricTexture"
.br
.ti -1c
.RI "#define \fBgluQuadricCallback\fP   mgluQuadricCallback"
.br
.ti -1c
.RI "#define \fBgluCylinder\fP   mgluCylinder"
.br
.ti -1c
.RI "#define \fBgluSphere\fP   mgluSphere"
.br
.ti -1c
.RI "#define \fBgluDisk\fP   mgluDisk"
.br
.ti -1c
.RI "#define \fBgluPartialDisk\fP   mgluPartialDisk"
.br
.ti -1c
.RI "#define \fBgluNewNurbsRenderer\fP   mgluNewNurbsRenderer"
.br
.ti -1c
.RI "#define \fBgluDeleteNurbsRenderer\fP   mgluDeleteNurbsRenderer"
.br
.ti -1c
.RI "#define \fBgluLoadSamplingMatrices\fP   mgluLoadSamplingMatrices"
.br
.ti -1c
.RI "#define \fBgluNurbsProperty\fP   mgluNurbsProperty"
.br
.ti -1c
.RI "#define \fBgluGetNurbsProperty\fP   mgluGetNurbsProperty"
.br
.ti -1c
.RI "#define \fBgluBeginCurve\fP   mgluBeginCurve"
.br
.ti -1c
.RI "#define \fBgluEndCurve\fP   mgluEndCurve"
.br
.ti -1c
.RI "#define \fBgluNurbsCurve\fP   mgluNurbsCurve"
.br
.ti -1c
.RI "#define \fBgluBeginSurface\fP   mgluBeginSurface"
.br
.ti -1c
.RI "#define \fBgluEndSurface\fP   mgluEndSurface"
.br
.ti -1c
.RI "#define \fBgluNurbsSurface\fP   mgluNurbsSurface"
.br
.ti -1c
.RI "#define \fBgluBeginTrim\fP   mgluBeginTrim"
.br
.ti -1c
.RI "#define \fBgluEndTrim\fP   mgluEndTrim"
.br
.ti -1c
.RI "#define \fBgluPwlCurve\fP   mgluPwlCurve"
.br
.ti -1c
.RI "#define \fBgluNurbsCallback\fP   mgluNurbsCallback"
.br
.ti -1c
.RI "#define \fBgluNewTess\fP   mgluNewTess"
.br
.ti -1c
.RI "#define \fBgluDeleteTess\fP   mgluDeleteTess"
.br
.ti -1c
.RI "#define \fBgluTessBeginPolygon\fP   mgluTessBeginPolygon"
.br
.ti -1c
.RI "#define \fBgluTessBeginContour\fP   mgluTessBeginContour"
.br
.ti -1c
.RI "#define \fBgluTessVertex\fP   mgluTessVertex"
.br
.ti -1c
.RI "#define \fBgluTessEndPolygon\fP   mgluTessEndPolygon"
.br
.ti -1c
.RI "#define \fBgluTessEndContour\fP   mgluTessEndContour"
.br
.ti -1c
.RI "#define \fBgluTessProperty\fP   mgluTessProperty"
.br
.ti -1c
.RI "#define \fBgluTessNormal\fP   mgluTessNormal"
.br
.ti -1c
.RI "#define \fBgluTessCallback\fP   mgluTessCallback"
.br
.ti -1c
.RI "#define \fBgluGetTessProperty\fP   mgluGetTessProperty"
.br
.ti -1c
.RI "#define \fBgluBeginPolygon\fP   mgluBeginPolygon"
.br
.ti -1c
.RI "#define \fBgluNextContour\fP   mgluNextContour"
.br
.ti -1c
.RI "#define \fBgluEndPolygon\fP   mgluEndPolygon"
.br
.ti -1c
.RI "#define \fBgluGetString\fP   mgluGetString"
.br
.ti -1c
.RI "#define \fBgluBuild1DMipmapLevels\fP   mgluBuild1DMipmapLevels"
.br
.ti -1c
.RI "#define \fBgluBuild2DMipmapLevels\fP   mgluBuild2DMipmapLevels"
.br
.ti -1c
.RI "#define \fBgluBuild3DMipmapLevels\fP   mgluBuild3DMipmapLevels"
.br
.ti -1c
.RI "#define \fBgluBuild3DMipmaps\fP   mgluBuild3DMipmaps"
.br
.ti -1c
.RI "#define \fBgluCheckExtension\fP   mgluCheckExtension"
.br
.ti -1c
.RI "#define \fBgluUnProject4\fP   mgluUnProject4"
.br
.ti -1c
.RI "#define \fBgluNurbsCallbackData\fP   mgluNurbsCallbackData"
.br
.ti -1c
.RI "#define \fBgluNurbsCallbackDataEXT\fP   mgluNurbsCallbackDataEXT"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define gluBeginCurve   mgluBeginCurve"

.PP
Définition à la ligne 52 du fichier glu_mangle\&.h\&.
.SS "#define gluBeginPolygon   mgluBeginPolygon"

.PP
Définition à la ligne 73 du fichier glu_mangle\&.h\&.
.SS "#define gluBeginSurface   mgluBeginSurface"

.PP
Définition à la ligne 55 du fichier glu_mangle\&.h\&.
.SS "#define gluBeginTrim   mgluBeginTrim"

.PP
Définition à la ligne 58 du fichier glu_mangle\&.h\&.
.SS "#define gluBuild1DMipmapLevels   mgluBuild1DMipmapLevels"

.PP
Définition à la ligne 77 du fichier glu_mangle\&.h\&.
.SS "#define gluBuild1DMipmaps   mgluBuild1DMipmaps"

.PP
Définition à la ligne 34 du fichier glu_mangle\&.h\&.
.SS "#define gluBuild2DMipmapLevels   mgluBuild2DMipmapLevels"

.PP
Définition à la ligne 78 du fichier glu_mangle\&.h\&.
.SS "#define gluBuild2DMipmaps   mgluBuild2DMipmaps"

.PP
Définition à la ligne 35 du fichier glu_mangle\&.h\&.
.SS "#define gluBuild3DMipmapLevels   mgluBuild3DMipmapLevels"

.PP
Définition à la ligne 79 du fichier glu_mangle\&.h\&.
.SS "#define gluBuild3DMipmaps   mgluBuild3DMipmaps"

.PP
Définition à la ligne 80 du fichier glu_mangle\&.h\&.
.SS "#define gluCheckExtension   mgluCheckExtension"

.PP
Définition à la ligne 81 du fichier glu_mangle\&.h\&.
.SS "#define gluCylinder   mgluCylinder"

.PP
Définition à la ligne 43 du fichier glu_mangle\&.h\&.
.SS "#define gluDeleteNurbsRenderer   mgluDeleteNurbsRenderer"

.PP
Définition à la ligne 48 du fichier glu_mangle\&.h\&.
.SS "#define gluDeleteQuadric   mgluDeleteQuadric"

.PP
Définition à la ligne 37 du fichier glu_mangle\&.h\&.
.SS "#define gluDeleteTess   mgluDeleteTess"

.PP
Définition à la ligne 63 du fichier glu_mangle\&.h\&.
.SS "#define gluDisk   mgluDisk"

.PP
Définition à la ligne 45 du fichier glu_mangle\&.h\&.
.SS "#define gluEndCurve   mgluEndCurve"

.PP
Définition à la ligne 53 du fichier glu_mangle\&.h\&.
.SS "#define gluEndPolygon   mgluEndPolygon"

.PP
Définition à la ligne 75 du fichier glu_mangle\&.h\&.
.SS "#define gluEndSurface   mgluEndSurface"

.PP
Définition à la ligne 56 du fichier glu_mangle\&.h\&.
.SS "#define gluEndTrim   mgluEndTrim"

.PP
Définition à la ligne 59 du fichier glu_mangle\&.h\&.
.SS "#define gluErrorString   mgluErrorString"

.PP
Définition à la ligne 32 du fichier glu_mangle\&.h\&.
.SS "#define gluGetNurbsProperty   mgluGetNurbsProperty"

.PP
Définition à la ligne 51 du fichier glu_mangle\&.h\&.
.SS "#define gluGetString   mgluGetString"

.PP
Définition à la ligne 76 du fichier glu_mangle\&.h\&.
.SS "#define gluGetTessProperty   mgluGetTessProperty"

.PP
Définition à la ligne 72 du fichier glu_mangle\&.h\&.
.SS "#define gluLoadSamplingMatrices   mgluLoadSamplingMatrices"

.PP
Définition à la ligne 49 du fichier glu_mangle\&.h\&.
.SS "#define gluLookAt   mgluLookAt"

.PP
Définition à la ligne 26 du fichier glu_mangle\&.h\&.
.SS "#define gluNewNurbsRenderer   mgluNewNurbsRenderer"

.PP
Définition à la ligne 47 du fichier glu_mangle\&.h\&.
.SS "#define gluNewQuadric   mgluNewQuadric"

.PP
Définition à la ligne 36 du fichier glu_mangle\&.h\&.
.SS "#define gluNewTess   mgluNewTess"

.PP
Définition à la ligne 62 du fichier glu_mangle\&.h\&.
.SS "#define gluNextContour   mgluNextContour"

.PP
Définition à la ligne 74 du fichier glu_mangle\&.h\&.
.SS "#define gluNurbsCallback   mgluNurbsCallback"

.PP
Définition à la ligne 61 du fichier glu_mangle\&.h\&.
.SS "#define gluNurbsCallbackData   mgluNurbsCallbackData"

.PP
Définition à la ligne 83 du fichier glu_mangle\&.h\&.
.SS "#define gluNurbsCallbackDataEXT   mgluNurbsCallbackDataEXT"

.PP
Définition à la ligne 84 du fichier glu_mangle\&.h\&.
.SS "#define gluNurbsCurve   mgluNurbsCurve"

.PP
Définition à la ligne 54 du fichier glu_mangle\&.h\&.
.SS "#define gluNurbsProperty   mgluNurbsProperty"

.PP
Définition à la ligne 50 du fichier glu_mangle\&.h\&.
.SS "#define gluNurbsSurface   mgluNurbsSurface"

.PP
Définition à la ligne 57 du fichier glu_mangle\&.h\&.
.SS "#define gluOrtho2D   mgluOrtho2D"

.PP
Définition à la ligne 27 du fichier glu_mangle\&.h\&.
.SS "#define gluPartialDisk   mgluPartialDisk"

.PP
Définition à la ligne 46 du fichier glu_mangle\&.h\&.
.SS "#define gluPerspective   mgluPerspective"

.PP
Définition à la ligne 28 du fichier glu_mangle\&.h\&.
.SS "#define gluPickMatrix   mgluPickMatrix"

.PP
Définition à la ligne 29 du fichier glu_mangle\&.h\&.
.SS "#define gluProject   mgluProject"

.PP
Définition à la ligne 30 du fichier glu_mangle\&.h\&.
.SS "#define gluPwlCurve   mgluPwlCurve"

.PP
Définition à la ligne 60 du fichier glu_mangle\&.h\&.
.SS "#define gluQuadricCallback   mgluQuadricCallback"

.PP
Définition à la ligne 42 du fichier glu_mangle\&.h\&.
.SS "#define gluQuadricDrawStyle   mgluQuadricDrawStyle"

.PP
Définition à la ligne 38 du fichier glu_mangle\&.h\&.
.SS "#define gluQuadricNormals   mgluQuadricNormals"

.PP
Définition à la ligne 40 du fichier glu_mangle\&.h\&.
.SS "#define gluQuadricOrientation   mgluQuadricOrientation"

.PP
Définition à la ligne 39 du fichier glu_mangle\&.h\&.
.SS "#define gluQuadricTexture   mgluQuadricTexture"

.PP
Définition à la ligne 41 du fichier glu_mangle\&.h\&.
.SS "#define gluScaleImage   mgluScaleImage"

.PP
Définition à la ligne 33 du fichier glu_mangle\&.h\&.
.SS "#define gluSphere   mgluSphere"

.PP
Définition à la ligne 44 du fichier glu_mangle\&.h\&.
.SS "#define gluTessBeginContour   mgluTessBeginContour"

.PP
Définition à la ligne 65 du fichier glu_mangle\&.h\&.
.SS "#define gluTessBeginPolygon   mgluTessBeginPolygon"

.PP
Définition à la ligne 64 du fichier glu_mangle\&.h\&.
.SS "#define gluTessCallback   mgluTessCallback"

.PP
Définition à la ligne 71 du fichier glu_mangle\&.h\&.
.SS "#define gluTessEndContour   mgluTessEndContour"

.PP
Définition à la ligne 68 du fichier glu_mangle\&.h\&.
.SS "#define gluTessEndPolygon   mgluTessEndPolygon"

.PP
Définition à la ligne 67 du fichier glu_mangle\&.h\&.
.SS "#define gluTessNormal   mgluTessNormal"

.PP
Définition à la ligne 70 du fichier glu_mangle\&.h\&.
.SS "#define gluTessProperty   mgluTessProperty"

.PP
Définition à la ligne 69 du fichier glu_mangle\&.h\&.
.SS "#define gluTessVertex   mgluTessVertex"

.PP
Définition à la ligne 66 du fichier glu_mangle\&.h\&.
.SS "#define gluUnProject   mgluUnProject"

.PP
Définition à la ligne 31 du fichier glu_mangle\&.h\&.
.SS "#define gluUnProject4   mgluUnProject4"

.PP
Définition à la ligne 82 du fichier glu_mangle\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
