.TH "/home/cj/workspace/Tetris/src/glut/glx_mangle.h" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/glut/glx_mangle.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBglXChooseVisual\fP   mglXChooseVisual"
.br
.ti -1c
.RI "#define \fBglXCreateContext\fP   mglXCreateContext"
.br
.ti -1c
.RI "#define \fBglXDestroyContext\fP   mglXDestroyContext"
.br
.ti -1c
.RI "#define \fBglXMakeCurrent\fP   mglXMakeCurrent"
.br
.ti -1c
.RI "#define \fBglXCopyContext\fP   mglXCopyContext"
.br
.ti -1c
.RI "#define \fBglXSwapBuffers\fP   mglXSwapBuffers"
.br
.ti -1c
.RI "#define \fBglXCreateGLXPixmap\fP   mglXCreateGLXPixmap"
.br
.ti -1c
.RI "#define \fBglXDestroyGLXPixmap\fP   mglXDestroyGLXPixmap"
.br
.ti -1c
.RI "#define \fBglXQueryExtension\fP   mglXQueryExtension"
.br
.ti -1c
.RI "#define \fBglXQueryVersion\fP   mglXQueryVersion"
.br
.ti -1c
.RI "#define \fBglXIsDirect\fP   mglXIsDirect"
.br
.ti -1c
.RI "#define \fBglXGetConfig\fP   mglXGetConfig"
.br
.ti -1c
.RI "#define \fBglXGetCurrentContext\fP   mglXGetCurrentContext"
.br
.ti -1c
.RI "#define \fBglXGetCurrentDrawable\fP   mglXGetCurrentDrawable"
.br
.ti -1c
.RI "#define \fBglXWaitGL\fP   mglXWaitGL"
.br
.ti -1c
.RI "#define \fBglXWaitX\fP   mglXWaitX"
.br
.ti -1c
.RI "#define \fBglXUseXFont\fP   mglXUseXFont"
.br
.ti -1c
.RI "#define \fBglXQueryExtensionsString\fP   mglXQueryExtensionsString"
.br
.ti -1c
.RI "#define \fBglXQueryServerString\fP   mglXQueryServerString"
.br
.ti -1c
.RI "#define \fBglXGetClientString\fP   mglXGetClientString"
.br
.ti -1c
.RI "#define \fBglXCreateGLXPixmapMESA\fP   mglXCreateGLXPixmapMESA"
.br
.ti -1c
.RI "#define \fBglXReleaseBuffersMESA\fP   mglXReleaseBuffersMESA"
.br
.ti -1c
.RI "#define \fBglXCopySubBufferMESA\fP   mglXCopySubBufferMESA"
.br
.ti -1c
.RI "#define \fBglXGetVideoSyncSGI\fP   mglXGetVideoSyncSGI"
.br
.ti -1c
.RI "#define \fBglXWaitVideoSyncSGI\fP   mglXWaitVideoSyncSGI"
.br
.ti -1c
.RI "#define \fBglXGetCurrentDisplay\fP   mglXGetCurrentDisplay"
.br
.ti -1c
.RI "#define \fBglXChooseFBConfig\fP   mglXChooseFBConfig"
.br
.ti -1c
.RI "#define \fBglXGetFBConfigAttrib\fP   mglXGetFBConfigAttrib"
.br
.ti -1c
.RI "#define \fBglXGetFBConfigs\fP   mglXGetFBConfigs"
.br
.ti -1c
.RI "#define \fBglXGetVisualFromFBConfig\fP   mglXGetVisualFromFBConfig"
.br
.ti -1c
.RI "#define \fBglXCreateWindow\fP   mglXCreateWindow"
.br
.ti -1c
.RI "#define \fBglXDestroyWindow\fP   mglXDestroyWindow"
.br
.ti -1c
.RI "#define \fBglXCreatePixmap\fP   mglXCreatePixmap"
.br
.ti -1c
.RI "#define \fBglXDestroyPixmap\fP   mglXDestroyPixmap"
.br
.ti -1c
.RI "#define \fBglXCreatePbuffer\fP   mglXCreatePbuffer"
.br
.ti -1c
.RI "#define \fBglXDestroyPbuffer\fP   mglXDestroyPbuffer"
.br
.ti -1c
.RI "#define \fBglXQueryDrawable\fP   mglXQueryDrawable"
.br
.ti -1c
.RI "#define \fBglXCreateNewContext\fP   mglXCreateNewContext"
.br
.ti -1c
.RI "#define \fBglXMakeContextCurrent\fP   mglXMakeContextCurrent"
.br
.ti -1c
.RI "#define \fBglXGetCurrentReadDrawable\fP   mglXGetCurrentReadDrawable"
.br
.ti -1c
.RI "#define \fBglXQueryContext\fP   mglXQueryContext"
.br
.ti -1c
.RI "#define \fBglXSelectEvent\fP   mglXSelectEvent"
.br
.ti -1c
.RI "#define \fBglXGetSelectedEvent\fP   mglXGetSelectedEvent"
.br
.ti -1c
.RI "#define \fBglXGetProcAddress\fP   mglXGetProcAddress"
.br
.ti -1c
.RI "#define \fBglXGetProcAddressARB\fP   mglXGetProcAddressARB"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define glXChooseFBConfig   mglXChooseFBConfig"

.PP
Définition à la ligne 59 du fichier glx_mangle\&.h\&.
.SS "#define glXChooseVisual   mglXChooseVisual"

.PP
Définition à la ligne 29 du fichier glx_mangle\&.h\&.
.SS "#define glXCopyContext   mglXCopyContext"

.PP
Définition à la ligne 33 du fichier glx_mangle\&.h\&.
.SS "#define glXCopySubBufferMESA   mglXCopySubBufferMESA"

.PP
Définition à la ligne 51 du fichier glx_mangle\&.h\&.
.SS "#define glXCreateContext   mglXCreateContext"

.PP
Définition à la ligne 30 du fichier glx_mangle\&.h\&.
.SS "#define glXCreateGLXPixmap   mglXCreateGLXPixmap"

.PP
Définition à la ligne 35 du fichier glx_mangle\&.h\&.
.SS "#define glXCreateGLXPixmapMESA   mglXCreateGLXPixmapMESA"

.PP
Définition à la ligne 49 du fichier glx_mangle\&.h\&.
.SS "#define glXCreateNewContext   mglXCreateNewContext"

.PP
Définition à la ligne 70 du fichier glx_mangle\&.h\&.
.SS "#define glXCreatePbuffer   mglXCreatePbuffer"

.PP
Définition à la ligne 67 du fichier glx_mangle\&.h\&.
.SS "#define glXCreatePixmap   mglXCreatePixmap"

.PP
Définition à la ligne 65 du fichier glx_mangle\&.h\&.
.SS "#define glXCreateWindow   mglXCreateWindow"

.PP
Définition à la ligne 63 du fichier glx_mangle\&.h\&.
.SS "#define glXDestroyContext   mglXDestroyContext"

.PP
Définition à la ligne 31 du fichier glx_mangle\&.h\&.
.SS "#define glXDestroyGLXPixmap   mglXDestroyGLXPixmap"

.PP
Définition à la ligne 36 du fichier glx_mangle\&.h\&.
.SS "#define glXDestroyPbuffer   mglXDestroyPbuffer"

.PP
Définition à la ligne 68 du fichier glx_mangle\&.h\&.
.SS "#define glXDestroyPixmap   mglXDestroyPixmap"

.PP
Définition à la ligne 66 du fichier glx_mangle\&.h\&.
.SS "#define glXDestroyWindow   mglXDestroyWindow"

.PP
Définition à la ligne 64 du fichier glx_mangle\&.h\&.
.SS "#define glXGetClientString   mglXGetClientString"

.PP
Définition à la ligne 48 du fichier glx_mangle\&.h\&.
.SS "#define glXGetConfig   mglXGetConfig"

.PP
Définition à la ligne 40 du fichier glx_mangle\&.h\&.
.SS "#define glXGetCurrentContext   mglXGetCurrentContext"

.PP
Définition à la ligne 41 du fichier glx_mangle\&.h\&.
.SS "#define glXGetCurrentDisplay   mglXGetCurrentDisplay"

.PP
Définition à la ligne 56 du fichier glx_mangle\&.h\&.
.SS "#define glXGetCurrentDrawable   mglXGetCurrentDrawable"

.PP
Définition à la ligne 42 du fichier glx_mangle\&.h\&.
.SS "#define glXGetCurrentReadDrawable   mglXGetCurrentReadDrawable"

.PP
Définition à la ligne 72 du fichier glx_mangle\&.h\&.
.SS "#define glXGetFBConfigAttrib   mglXGetFBConfigAttrib"

.PP
Définition à la ligne 60 du fichier glx_mangle\&.h\&.
.SS "#define glXGetFBConfigs   mglXGetFBConfigs"

.PP
Définition à la ligne 61 du fichier glx_mangle\&.h\&.
.SS "#define glXGetProcAddress   mglXGetProcAddress"

.PP
Définition à la ligne 78 du fichier glx_mangle\&.h\&.
.SS "#define glXGetProcAddressARB   mglXGetProcAddressARB"

.PP
Définition à la ligne 79 du fichier glx_mangle\&.h\&.
.SS "#define glXGetSelectedEvent   mglXGetSelectedEvent"

.PP
Définition à la ligne 75 du fichier glx_mangle\&.h\&.
.SS "#define glXGetVideoSyncSGI   mglXGetVideoSyncSGI"

.PP
Définition à la ligne 52 du fichier glx_mangle\&.h\&.
.SS "#define glXGetVisualFromFBConfig   mglXGetVisualFromFBConfig"

.PP
Définition à la ligne 62 du fichier glx_mangle\&.h\&.
.SS "#define glXIsDirect   mglXIsDirect"

.PP
Définition à la ligne 39 du fichier glx_mangle\&.h\&.
.SS "#define glXMakeContextCurrent   mglXMakeContextCurrent"

.PP
Définition à la ligne 71 du fichier glx_mangle\&.h\&.
.SS "#define glXMakeCurrent   mglXMakeCurrent"

.PP
Définition à la ligne 32 du fichier glx_mangle\&.h\&.
.SS "#define glXQueryContext   mglXQueryContext"

.PP
Définition à la ligne 73 du fichier glx_mangle\&.h\&.
.SS "#define glXQueryDrawable   mglXQueryDrawable"

.PP
Définition à la ligne 69 du fichier glx_mangle\&.h\&.
.SS "#define glXQueryExtension   mglXQueryExtension"

.PP
Définition à la ligne 37 du fichier glx_mangle\&.h\&.
.SS "#define glXQueryExtensionsString   mglXQueryExtensionsString"

.PP
Définition à la ligne 46 du fichier glx_mangle\&.h\&.
.SS "#define glXQueryServerString   mglXQueryServerString"

.PP
Définition à la ligne 47 du fichier glx_mangle\&.h\&.
.SS "#define glXQueryVersion   mglXQueryVersion"

.PP
Définition à la ligne 38 du fichier glx_mangle\&.h\&.
.SS "#define glXReleaseBuffersMESA   mglXReleaseBuffersMESA"

.PP
Définition à la ligne 50 du fichier glx_mangle\&.h\&.
.SS "#define glXSelectEvent   mglXSelectEvent"

.PP
Définition à la ligne 74 du fichier glx_mangle\&.h\&.
.SS "#define glXSwapBuffers   mglXSwapBuffers"

.PP
Définition à la ligne 34 du fichier glx_mangle\&.h\&.
.SS "#define glXUseXFont   mglXUseXFont"

.PP
Définition à la ligne 45 du fichier glx_mangle\&.h\&.
.SS "#define glXWaitGL   mglXWaitGL"

.PP
Définition à la ligne 43 du fichier glx_mangle\&.h\&.
.SS "#define glXWaitVideoSyncSGI   mglXWaitVideoSyncSGI"

.PP
Définition à la ligne 53 du fichier glx_mangle\&.h\&.
.SS "#define glXWaitX   mglXWaitX"

.PP
Définition à la ligne 44 du fichier glx_mangle\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
