.TH "GLXBufferClobberEventSGIX" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXBufferClobberEventSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "int \fBevent_type\fP"
.br
.ti -1c
.RI "int \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned int \fBmask\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 461 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "int GLXBufferClobberEventSGIX::count"

.PP
Définition à la ligne 472 du fichier glxext\&.h\&.
.SS "Display* GLXBufferClobberEventSGIX::display"

.PP
Définition à la ligne 465 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::draw_type"

.PP
Définition à la ligne 468 du fichier glxext\&.h\&.
.SS "\fBGLXDrawable\fP GLXBufferClobberEventSGIX::drawable"

.PP
Définition à la ligne 466 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::event_type"

.PP
Définition à la ligne 467 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::height"

.PP
Définition à la ligne 471 du fichier glxext\&.h\&.
.SS "unsigned int GLXBufferClobberEventSGIX::mask"

.PP
Définition à la ligne 469 du fichier glxext\&.h\&.
.SS "Bool GLXBufferClobberEventSGIX::send_event"

.PP
Définition à la ligne 464 du fichier glxext\&.h\&.
.SS "unsigned long GLXBufferClobberEventSGIX::serial"

.PP
Définition à la ligne 463 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::type"

.PP
Définition à la ligne 462 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::width"

.PP
Définition à la ligne 471 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::x"

.PP
Définition à la ligne 470 du fichier glxext\&.h\&.
.SS "int GLXBufferClobberEventSGIX::y"

.PP
Définition à la ligne 470 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
