.TH "GLXBufferSwapComplete" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXBufferSwapComplete \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glx\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "int \fBevent_type\fP"
.br
.ti -1c
.RI "int64_t \fBust\fP"
.br
.ti -1c
.RI "int64_t \fBmsc\fP"
.br
.ti -1c
.RI "int64_t \fBsbc\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 504 du fichier glx\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "Display* GLXBufferSwapComplete::display"

.PP
Définition à la ligne 508 du fichier glx\&.h\&.
.SS "\fBGLXDrawable\fP GLXBufferSwapComplete::drawable"

.PP
Définition à la ligne 509 du fichier glx\&.h\&.
.SS "int GLXBufferSwapComplete::event_type"

.PP
Définition à la ligne 510 du fichier glx\&.h\&.
.SS "int64_t GLXBufferSwapComplete::msc"

.PP
Définition à la ligne 512 du fichier glx\&.h\&.
.SS "int64_t GLXBufferSwapComplete::sbc"

.PP
Définition à la ligne 513 du fichier glx\&.h\&.
.SS "Bool GLXBufferSwapComplete::send_event"

.PP
Définition à la ligne 507 du fichier glx\&.h\&.
.SS "unsigned long GLXBufferSwapComplete::serial"

.PP
Définition à la ligne 506 du fichier glx\&.h\&.
.SS "int GLXBufferSwapComplete::type"

.PP
Définition à la ligne 505 du fichier glx\&.h\&.
.SS "int64_t GLXBufferSwapComplete::ust"

.PP
Définition à la ligne 511 du fichier glx\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
