.TH "GLXHyperpipeNetworkSGIX" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXHyperpipeNetworkSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "int \fBnetworkId\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 832 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "int GLXHyperpipeNetworkSGIX::networkId"

.PP
Définition à la ligne 834 du fichier glxext\&.h\&.
.SS "char GLXHyperpipeNetworkSGIX::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 833 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
