.TH "GLXPipeRect" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "int \fBsrcXOrigin\fP"
.br
.ti -1c
.RI "int \fBsrcYOrigin\fP"
.br
.ti -1c
.RI "int \fBsrcWidth\fP"
.br
.ti -1c
.RI "int \fBsrcHeight\fP"
.br
.ti -1c
.RI "int \fBdestXOrigin\fP"
.br
.ti -1c
.RI "int \fBdestYOrigin\fP"
.br
.ti -1c
.RI "int \fBdestWidth\fP"
.br
.ti -1c
.RI "int \fBdestHeight\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 845 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "int GLXPipeRect::destHeight"

.PP
Définition à la ligne 848 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::destWidth"

.PP
Définition à la ligne 848 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::destXOrigin"

.PP
Définition à la ligne 848 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::destYOrigin"

.PP
Définition à la ligne 848 du fichier glxext\&.h\&.
.SS "char GLXPipeRect::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 846 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::srcHeight"

.PP
Définition à la ligne 847 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::srcWidth"

.PP
Définition à la ligne 847 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::srcXOrigin"

.PP
Définition à la ligne 847 du fichier glxext\&.h\&.
.SS "int GLXPipeRect::srcYOrigin"

.PP
Définition à la ligne 847 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
