.TH "GLXPipeRectLimits" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRectLimits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "int \fBXOrigin\fP"
.br
.ti -1c
.RI "int \fBYOrigin\fP"
.br
.ti -1c
.RI "int \fBmaxHeight\fP"
.br
.ti -1c
.RI "int \fBmaxWidth\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 851 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "int GLXPipeRectLimits::maxHeight"

.PP
Définition à la ligne 853 du fichier glxext\&.h\&.
.SS "int GLXPipeRectLimits::maxWidth"

.PP
Définition à la ligne 853 du fichier glxext\&.h\&.
.SS "char GLXPipeRectLimits::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 852 du fichier glxext\&.h\&.
.SS "int GLXPipeRectLimits::XOrigin"

.PP
Définition à la ligne 853 du fichier glxext\&.h\&.
.SS "int GLXPipeRectLimits::YOrigin"

.PP
Définition à la ligne 853 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
