.TH "GLXPbufferClobberEvent" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPbufferClobberEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glx\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBevent_type\fP"
.br
.ti -1c
.RI "int \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "unsigned int \fBbuffer_mask\fP"
.br
.ti -1c
.RI "unsigned int \fBaux_buffer\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 490 du fichier glx\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned int GLXPbufferClobberEvent::aux_buffer"

.PP
Définition à la ligne 498 du fichier glx\&.h\&.
.SS "unsigned int GLXPbufferClobberEvent::buffer_mask"

.PP
Définition à la ligne 497 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::count"

.PP
Définition à la ligne 501 du fichier glx\&.h\&.
.SS "Display* GLXPbufferClobberEvent::display"

.PP
Définition à la ligne 495 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::draw_type"

.PP
Définition à la ligne 492 du fichier glx\&.h\&.
.SS "\fBGLXDrawable\fP GLXPbufferClobberEvent::drawable"

.PP
Définition à la ligne 496 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::event_type"

.PP
Définition à la ligne 491 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::height"

.PP
Définition à la ligne 500 du fichier glx\&.h\&.
.SS "Bool GLXPbufferClobberEvent::send_event"

.PP
Définition à la ligne 494 du fichier glx\&.h\&.
.SS "unsigned long GLXPbufferClobberEvent::serial"

.PP
Définition à la ligne 493 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::width"

.PP
Définition à la ligne 500 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::x"

.PP
Définition à la ligne 499 du fichier glx\&.h\&.
.SS "int GLXPbufferClobberEvent::y"

.PP
Définition à la ligne 499 du fichier glx\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
