.TH "Helpers" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helpers \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Fonctions membres publiques statiques"

.in +1c
.ti -1c
.RI "static unsigned int \fBFindSubStrCount\fP (const \fBstd::string\fP &str, const \fBstd::string\fP &subStr)"
.br
.ti -1c
.RI "static std::vector< \fBstd::string\fP > \fBSplit\fP (const \fBstd::string\fP &\fBsrc\fP, const char delim)"
.br
.RI "\fIsplit a string by an other string \fP"
.ti -1c
.RI "template<class T > static \fBstd::string\fP \fBToString\fP (const \fBT\fP &\fBvalue\fP)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure qui regroupe des petites fonctions utiles 
.PP
Définition à la ligne 102 du fichier Common\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "static unsigned int Helpers::FindSubStrCount (const \fBstd::string\fP &str, const \fBstd::string\fP &subStr)\fC [inline]\fP, \fC [static]\fP"

.PP
Définition à la ligne 107 du fichier Common\&.h\&.
.SS "static std::vector<\fBstd::string\fP> Helpers::Split (const \fBstd::string\fP &src, const chardelim)\fC [inline]\fP, \fC [static]\fP"

.PP
split a string by an other string \fBParamètres:\fP
.RS 4
\fIthe\fP string we want split 
.br
\fIthe\fP splitter substring 
.RE
.PP
\fBRenvoie:\fP
.RS 4
a string vector splited 
.RE
.PP

.PP
Définition à la ligne 126 du fichier Common\&.h\&.
.SS "template<class T > static \fBstd::string\fP Helpers::ToString (const \fBT\fP &value)\fC [inline]\fP, \fC [static]\fP"

.PP
Définition à la ligne 149 du fichier Common\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
