.TH "RendererSetup" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RendererSetup \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBRendererSetup\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetClearColor\fP (float red, float \fBgreen\fP, float \fBblue\fP, float \fBalpha\fP)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "bool \fBm_drawGround\fP"
.br
.ti -1c
.RI "float \fBm_clearColor\fP [4]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 59 du fichier Common\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "RendererSetup::RendererSetup ()\fC [inline]\fP"

.PP
Définition à la ligne 61 du fichier Common\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP RendererSetup::SetClearColor (floatred, floatgreen, floatblue, floatalpha)\fC [inline]\fP"

.PP
Définition à la ligne 72 du fichier Common\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "float RendererSetup::m_clearColor[4]"

.PP
Définition à la ligne 81 du fichier Common\&.h\&.
.SS "bool RendererSetup::m_drawGround"

.PP
Définition à la ligne 80 du fichier Common\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
