.TH "STLDelete" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STLDelete \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "template<class T > \fBvoid\fP \fBoperator()\fP (\fBT\fP *&\fBp\fP) const "
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 88 du fichier Common\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T > \fBvoid\fP STLDelete::operator() (\fBT\fP *&p) const\fC [inline]\fP"

.PP
Définition à la ligne 90 du fichier Common\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
