.TH "/home/cj/workspace/Tetris/src/test/testCOPiece.cpp" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/cj/workspace/Tetris/src/test/testCOPiece.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'COPiece\&.h'\fP
.br
\fC#include 'testCOPiece/CProjetTetrisPiece\&.h'\fP
.br
\fC#include 'CGuiGlut\&.h'\fP
.br
\fC#include 'test\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Définition à la ligne 6 du fichier testCOPiece\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
