.TH "todo" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Liste des choses à faire 
.IP "\fBClasse \fB__DRIversionRec\fP \fP" 1c
There are several data structures that explicitly store a major version, minor version, and patch level\&. These structures should be modified to have a \fC\fB__DRIversionRec\fP\fP instead\&. 
.PP

