.TH "UserEvents" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserEvents \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBUserEvents\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBClearKeyBardEvents\fP ()"
.br
.ti -1c
.RI "bool \fBIsPressed\fP (\fBKey\fP key)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBmousex\fP"
.br
.ti -1c
.RI "int \fBmousey\fP"
.br
.ti -1c
.RI "int \fBmousexrel\fP"
.br
.ti -1c
.RI "int \fBmouseyrel\fP"
.br
.ti -1c
.RI "int \fBmousebuttons\fP [6]"
.br
.ti -1c
.RI "std::vector< bool > \fBm_keyBoardEvents\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 424 du fichier Common\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "UserEvents::UserEvents ()\fC [inline]\fP"

.PP
Définition à la ligne 430 du fichier Common\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP UserEvents::ClearKeyBardEvents ()\fC [inline]\fP"

.PP
Définition à la ligne 439 du fichier Common\&.h\&.
.SS "bool UserEvents::IsPressed (\fBKey\fPkey)\fC [inline]\fP"

.PP
Définition à la ligne 446 du fichier Common\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "std::vector<bool> UserEvents::m_keyBoardEvents"

.PP
Définition à la ligne 451 du fichier Common\&.h\&.
.SS "int UserEvents::mousebuttons[6]"

.PP
Définition à la ligne 428 du fichier Common\&.h\&.
.SS "int UserEvents::mousex"

.PP
Définition à la ligne 426 du fichier Common\&.h\&.
.SS "int UserEvents::mousexrel"

.PP
Définition à la ligne 427 du fichier Common\&.h\&.
.SS "int UserEvents::mousey"

.PP
Définition à la ligne 426 du fichier Common\&.h\&.
.SS "int UserEvents::mouseyrel"

.PP
Définition à la ligne 427 du fichier Common\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
