.TH "WindowSetup" 3 "Vendredi Février 21 2014" "Version alpha" "Tetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowSetup \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Common\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBWindowSetup\fP ()"
.br
.ti -1c
.RI "\fBWindowSetup\fP (int \fBwidth\fP, int \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSize\fP (int \fBwidth\fP, int \fBheight\fP)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBm_width\fP"
.br
.ti -1c
.RI "int \fBm_height\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 42 du fichier Common\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "WindowSetup::WindowSetup ()\fC [inline]\fP"

.PP
Définition à la ligne 44 du fichier Common\&.h\&.
.SS "WindowSetup::WindowSetup (intwidth, intheight)\fC [inline]\fP"

.PP
Définition à la ligne 46 du fichier Common\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP WindowSetup::SetSize (intwidth, intheight)\fC [inline]\fP"

.PP
Définition à la ligne 49 du fichier Common\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "int WindowSetup::m_height"

.PP
Définition à la ligne 51 du fichier Common\&.h\&.
.SS "int WindowSetup::m_width"

.PP
Définition à la ligne 51 du fichier Common\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Tetris à partir du code source\&.
